
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace BadwordFilterMLModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            BadwordFilterMLModel.ModelInput sampleData = new BadwordFilterMLModel.ModelInput()
            {
                Text = @"Cao Lãnh với chúng tôi làyy",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = BadwordFilterMLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label_ID with predicted Label_ID from sample data...\n\n");


            Console.WriteLine($"Text: {@"Cao Lãnh với chúng tôi làyy"}");
            Console.WriteLine($"Label_ID: {0F}");


            Console.WriteLine($"\n\nPredicted Label_ID: {predictionResult.PredictedLabel}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
